/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kiosk;

import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Aasna
 */
public class AddEvent extends javax.swing.JFrame {

    Connection con = null;
    Statement stmt = null;
    PreparedStatement ps = null;

    /**
     * Creates new form AddEvent
     */
    public AddEvent() {
        initComponents();
        System.out.print("running");

    }

    public void inserting_event() throws ParseException {
        String event_add1 = event_add.getText();
        String location_add1 = location_add.getText();
        String time_add1 = time_add.getText();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        date_add.setFormats(dateFormat);
        String date_to_store = dateFormat.format(date_add.getDate()).toString();
        String desc_add1 = desc_add.getText();
        System.out.print(event_add.getText());
        System.out.print(location_add.getText());
        System.out.print(event_add1.length());
        System.out.print(date_to_store);
        String dateFormatted = "TO_DATE('"+date_to_store+"', 'DD-MM-YYYY')";

        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "system", "123456");
            stmt = con.createStatement();
            System.out.print("a");
            ResultSet rs = stmt.executeQuery("INSERT INTO EVENT(EVENT_ID,EVENT_NAME,LOCATION,TIME,EVENT_DATE,DESCRIPTION) VALUES('156','" + event_add1 + "','" + location_add1 + "','12',"+"TO_DATE('"+date_to_store+"', 'DD-MM-YYYY'),'" + desc_add1 + "')");
            JOptionPane.showMessageDialog(null, "Event Inserted Successfully!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "ERROR");
        }
    }

    public void getInfo() throws SQLException {
        con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "system", "123456");
        stmt = con.createStatement();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        time_add = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        date_add = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        event_add = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        location_add = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc_add = new javax.swing.JTextArea();
        add_event = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\concertpic.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 900));
        setPreferredSize(new java.awt.Dimension(700, 900));
        getContentPane().setLayout(null);

        time_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time_addActionPerformed(evt);
            }
        });
        getContentPane().add(time_add);
        time_add.setBounds(210, 270, 230, 30);

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 40, 73, 23);

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel3.setText("ADD EVENTS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 110, 130, 40);
        getContentPane().add(date_add);
        date_add.setBounds(210, 320, 230, 30);

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel4.setText("Event Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 180, 100, 19);

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel5.setText("Location");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 230, 70, 20);
        getContentPane().add(event_add);
        event_add.setBounds(210, 170, 230, 30);

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel6.setText("Date");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 330, 50, 20);

        jLabel10.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel10.setText("Time");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, 280, 50, 20);

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel7.setText("Description");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 370, 100, 20);

        location_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                location_addActionPerformed(evt);
            }
        });
        getContentPane().add(location_add);
        location_add.setBounds(210, 220, 230, 30);

        desc_add.setColumns(20);
        desc_add.setRows(5);
        jScrollPane1.setViewportView(desc_add);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(210, 370, 230, 137);

        add_event.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        add_event.setText("Add");
        add_event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_eventActionPerformed(evt);
            }
        });
        getContentPane().add(add_event);
        add_event.setBounds(280, 520, 80, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Photoshop Images\\KIosksmallLogo.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 10, 100, 110);

        jLabel8.setFont(new java.awt.Font("Sofachrome Rg", 0, 24)); // NOI18N
        jLabel8.setText("KIOSK");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 50, 128, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/concertpic.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 510, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void location_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_location_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_location_addActionPerformed

    private void add_eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_eventActionPerformed
        try {
            inserting_event();        // TODO add your handling code here:
        } catch (ParseException ex) {
            Logger.getLogger(AddEvent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_add_eventActionPerformed

    private void time_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_time_addActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(false);
Kiosk_Register kreg= new Kiosk_Register();
kreg.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_event;
    private org.jdesktop.swingx.JXDatePicker date_add;
    private javax.swing.JTextArea desc_add;
    private javax.swing.JTextField event_add;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField location_add;
    private javax.swing.JTextField time_add;
    // End of variables declaration//GEN-END:variables
}
