/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kiosk;

import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class GUI_Kiosk extends javax.swing.JFrame {

   
  Connection con1=null;
    Statement st1=null;
    PreparedStatement ps1= null;
    ResultSet rs=null;
    public GUI_Kiosk() {
        initComponents();
        showTableData();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Hometab = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        seebtn1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        seebtn2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        seebtn3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        seebtn4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        seebtn5 = new javax.swing.JButton();
        Eventstab = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        clzevent = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        cmtevent = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Gallerytab = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        cmtimg = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        clzimg = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        Helptab = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        Userstab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        std_id = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel37 = new javax.swing.JLabel();
        pwd = new javax.swing.JPasswordField();
        btnsrch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 900));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        jTabbedPane1.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N

        Hometab.setFont(new java.awt.Font("Chiller", 1, 14)); // NOI18N
        Hometab.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/priscilla-du-preez-775570-unsplash.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 204)));
        Hometab.add(jLabel6);
        jLabel6.setBounds(0, 128, 205, 190);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/martins-zemlickis-57243-unsplash.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 204)));
        Hometab.add(jLabel5);
        jLabel5.setBounds(248, 127, 202, 190);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/md-duran-628456-unsplash.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 204)));
        Hometab.add(jLabel7);
        jLabel7.setBounds(493, 127, 192, 190);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/kal-visuals-705792-unsplash.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 204)));
        Hometab.add(jLabel8);
        jLabel8.setBounds(736, 127, 188, 190);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/Football.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 204)));
        Hometab.add(jLabel9);
        jLabel9.setBounds(970, 130, 193, 190);

        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.setFont(new java.awt.Font("Chiller", 3, 36)); // NOI18N
        jTextField1.setText("TOP 5 EVENTS");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        Hometab.add(jTextField1);
        jTextField1.setBounds(489, 43, 196, 48);

        jButton1.setFont(new java.awt.Font("Chiller", 3, 24)); // NOI18N
        jButton1.setText("Change Events");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Hometab.add(jButton1);
        jButton1.setBounds(1000, 400, 160, 37);

        jLabel10.setFont(new java.awt.Font("Baskerville Old Face", 3, 18)); // NOI18N
        jLabel10.setText("The Musical Night");
        Hometab.add(jLabel10);
        jLabel10.setBounds(20, 320, 160, 30);

        seebtn1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seebtn1.setText("see details");
        Hometab.add(seebtn1);
        seebtn1.setBounds(50, 350, 100, 23);

        jLabel13.setFont(new java.awt.Font("Baskerville Old Face", 3, 18)); // NOI18N
        jLabel13.setText("The Marathon");
        Hometab.add(jLabel13);
        jLabel13.setBounds(290, 320, 130, 19);

        seebtn2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seebtn2.setText("see details");
        Hometab.add(seebtn2);
        seebtn2.setBounds(310, 350, 93, 23);

        jLabel14.setFont(new java.awt.Font("Baskerville Old Face", 3, 18)); // NOI18N
        jLabel14.setText("The Graduation Ceremony");
        Hometab.add(jLabel14);
        jLabel14.setBounds(480, 320, 220, 19);

        seebtn3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seebtn3.setText("see details");
        Hometab.add(seebtn3);
        seebtn3.setBounds(540, 350, 100, 23);

        jLabel15.setFont(new java.awt.Font("Baskerville Old Face", 3, 18)); // NOI18N
        jLabel15.setText("Movie Making");
        Hometab.add(jLabel15);
        jLabel15.setBounds(770, 320, 120, 19);

        seebtn4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seebtn4.setText("see details");
        Hometab.add(seebtn4);
        seebtn4.setBounds(780, 350, 93, 23);

        jLabel16.setFont(new java.awt.Font("Baskerville Old Face", 3, 18)); // NOI18N
        jLabel16.setText("Sports Events");
        Hometab.add(jLabel16);
        jLabel16.setBounds(1010, 320, 120, 19);

        seebtn5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seebtn5.setText("see details");
        Hometab.add(seebtn5);
        seebtn5.setBounds(1020, 350, 100, 23);

        jTabbedPane1.addTab("Home", Hometab);

        jTabbedPane2.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        clzevent.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        jTable4.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Event Name", "Event Location", "Event Time", "Event Description", "Title 5"
            }
        ));
        jScrollPane7.setViewportView(jTable4);

        javax.swing.GroupLayout clzeventLayout = new javax.swing.GroupLayout(clzevent);
        clzevent.setLayout(clzeventLayout);
        clzeventLayout.setHorizontalGroup(
            clzeventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1190, Short.MAX_VALUE)
        );
        clzeventLayout.setVerticalGroup(
            clzeventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("College Events", clzevent);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        javax.swing.GroupLayout cmteventLayout = new javax.swing.GroupLayout(cmtevent);
        cmtevent.setLayout(cmteventLayout);
        cmteventLayout.setHorizontalGroup(
            cmteventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmteventLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
                .addContainerGap())
        );
        cmteventLayout.setVerticalGroup(
            cmteventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Community Events", cmtevent);

        javax.swing.GroupLayout EventstabLayout = new javax.swing.GroupLayout(Eventstab);
        Eventstab.setLayout(EventstabLayout);
        EventstabLayout.setHorizontalGroup(
            EventstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        EventstabLayout.setVerticalGroup(
            EventstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Events", Eventstab);

        jTabbedPane3.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable2);

        javax.swing.GroupLayout cmtimgLayout = new javax.swing.GroupLayout(cmtimg);
        cmtimg.setLayout(cmtimgLayout);
        cmtimgLayout.setHorizontalGroup(
            cmtimgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmtimgLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
                .addContainerGap())
        );
        cmtimgLayout.setVerticalGroup(
            cmtimgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmtimgLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 179, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Community Events Images", cmtimg);

        clzimg.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Club Events", "Students Nghts", "Club Events", "Workshops"
            }
        ));
        jScrollPane6.setViewportView(jTable3);

        javax.swing.GroupLayout clzimgLayout = new javax.swing.GroupLayout(clzimg);
        clzimg.setLayout(clzimgLayout);
        clzimgLayout.setHorizontalGroup(
            clzimgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clzimgLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
                .addContainerGap())
        );
        clzimgLayout.setVerticalGroup(
            clzimgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clzimgLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 179, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("College Events Images", clzimg);

        jScrollPane3.setViewportView(jTabbedPane3);
        jTabbedPane3.getAccessibleContext().setAccessibleName("Community Events Images");

        javax.swing.GroupLayout GallerytabLayout = new javax.swing.GroupLayout(Gallerytab);
        Gallerytab.setLayout(GallerytabLayout);
        GallerytabLayout.setHorizontalGroup(
            GallerytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE)
        );
        GallerytabLayout.setVerticalGroup(
            GallerytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GallerytabLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Gallery", Gallerytab);

        Helptab.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("How can we help you?");

        jLabel17.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel17.setText("Do you need help in login or registration?");

        jLabel36.setBackground(new java.awt.Color(153, 153, 255));
        jLabel36.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 51, 204));
        jLabel36.setText("Drop your problems and we will find suggestions for you....");

        javax.swing.GroupLayout HelptabLayout = new javax.swing.GroupLayout(Helptab);
        Helptab.setLayout(HelptabLayout);
        HelptabLayout.setHorizontalGroup(
            HelptabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HelptabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HelptabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel17)
                    .addComponent(jLabel36))
                .addContainerGap(566, Short.MAX_VALUE))
        );
        HelptabLayout.setVerticalGroup(
            HelptabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HelptabLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(168, 168, 168)
                .addComponent(jLabel17)
                .addGap(140, 140, 140)
                .addComponent(jLabel36)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Help", Helptab);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel38.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel38.setText("User's Information");

        jLabel39.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel39.setText("Student id");

        jLabel40.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel40.setText("User Name");

        jLabel41.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel41.setText("Email");

        std_id.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        username.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        email.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        btndelete.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnupdate.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        Table.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student_id", "User Name", "Password", "Email"
            }
        ));
        jScrollPane2.setViewportView(Table);

        jLabel37.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel37.setText("Password");

        btnsrch.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnsrch.setText("Search");
        btnsrch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsrchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel38))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btndelete)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel40)
                                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel37)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(btnupdate))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(std_id, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(username)
                                    .addComponent(email)
                                    .addComponent(pwd))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnsrch, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel38)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(std_id, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsrch))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btndelete)
                            .addComponent(btnupdate)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout UserstabLayout = new javax.swing.GroupLayout(Userstab);
        Userstab.setLayout(UserstabLayout);
        UserstabLayout.setHorizontalGroup(
            UserstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE)
        );
        UserstabLayout.setVerticalGroup(
            UserstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Users", Userstab);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/KIosksmallLogo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("KIOSK");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel11.setText("Kiosk at your service.");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel12.setText("Online platform to get all the events information.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel3.setText("XYZ's Name");

        btnlogout.setFont(new java.awt.Font("Chiller", 1, 18)); // NOI18N
        btnlogout.setText("Log Out");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(btnlogout))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4010, 4010, 4010))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnsrchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsrchActionPerformed
         try{
             Class.forName("oracle.jdbc.driver.OracleDriver");
            con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","123456");
            st1= con1.createStatement();
            String sid=std_id.getText();
             System.out.println(sid);
           
//             ps1.setString(1, std_id.getText());
        rs = st1.executeQuery("SELECT * FROM REGISTER WHERE STUDENT_NO='"+sid+"'");
        if (rs.next()){
        username.setText(rs.getString("STUDENT_USERNAME"));
        pwd.setText(rs.getString("STUDENT_PASSWORD"));
        email.setText(rs.getString("STUDENT_EMAIL"));
        }
        
        
        }
        catch(Exception ex){
        JOptionPane.showMessageDialog(null,ex);
        
    }
    }//GEN-LAST:event_btnsrchActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","123456");
            st1= con1.createStatement();
            String sql="DELETE FROM REGISTER WHERE STUDENT_NO=?";
             ps1.setString(1, std_id.getText());
            ps1=con1.prepareStatement(sql);
        rs=ps1.executeQuery();
        rs.close();
        con1.close();
        }
        catch(Exception ex){
        JOptionPane.showMessageDialog(null,ex);
        
    }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
     try{
         Class.forName("oracle.jdbc.driver.OracleDriver");
        con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","123456");
        st1= con1.createStatement();
        String sql="UPDATE REGISTER SET STUDENT_USERNAME=?, STUDENT_PASSWORD=?, STUDENT_EMAIL=? where STUDENT_NO=?";
        ps1=con1.prepareStatement(sql);
        ps1.setString(4, std_id.getText());
        ps1.setString(1, username.getText());
        ps1.setString(2, pwd.getText());
        ps1.setString(3, email.getText());
        rs=ps1.executeQuery();
        showTableData();
        
        rs.close();
        con1.close();
    }
    catch(Exception ex){
        JOptionPane.showMessageDialog(null,ex);
        
    }
    }//GEN-LAST:event_btnupdateActionPerformed

   public void showTableData(){
    try{
        Class.forName("oracle.jdbc.driver.OracleDriver");
        con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","123456");
        st1= con1.createStatement();
      
        rs = st1.executeQuery("select * from REGISTER");
        System.out.print("running");
        Table.setModel(DbUtils.resultSetToTableModel(rs));
      }
    catch(Exception ex){
        JOptionPane.showMessageDialog(null,ex);
        
    }
   }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Kiosk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Kiosk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Kiosk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Kiosk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Kiosk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Eventstab;
    private javax.swing.JPanel Gallerytab;
    private javax.swing.JPanel Helptab;
    private javax.swing.JPanel Hometab;
    private javax.swing.JTable Table;
    private javax.swing.JPanel Userstab;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnsrch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JPanel clzevent;
    private javax.swing.JPanel clzimg;
    private javax.swing.JPanel cmtevent;
    private javax.swing.JPanel cmtimg;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JButton seebtn1;
    private javax.swing.JButton seebtn2;
    private javax.swing.JButton seebtn3;
    private javax.swing.JButton seebtn4;
    private javax.swing.JButton seebtn5;
    private javax.swing.JTextField std_id;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
