package kiosk;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 
 */
import java.sql.*;
import static java.util.logging.Logger.global;
import javax.swing.JOptionPane;
public class Kiosk_Log extends javax.swing.JFrame {
    Connection con = null;
    Statement stmt = null;
    PreparedStatement ps = null;
    static String studentlog_;

    /**
     * Creates new form Kiosk_Log
     */
    public Kiosk_Log() {
        initComponents();
        setDefaultCloseOperation(Kiosk_Log.DISPOSE_ON_CLOSE);
        
        
    }

    public void null_check()
    {
        String userlog1=student_log.getText();
        String passlog1=password_log.getText();
        if (userlog1 == " " || passlog1==" ")
        {
            JOptionPane.showMessageDialog(null, "Please fill out all the fields");
        } else {
            login_check();
        }
    }
    public void login_check()
    {
        String studentlog= student_log.getText();
        studentlog_=studentlog;
        String passlog=password_log.getText();
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "system", "123456");
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM REGISTER WHERE STUDENT_NO='"+studentlog+"' AND STUDENT_PASSWORD='"+passlog+"'");
            
            if (rs.next())
            {
                JOptionPane.showMessageDialog(null,"Login Successful");
                this.setVisible(false);
                Home_Login hlogin=new Home_Login();
                hlogin.setVisible(true);
            }
           
            else
            {
                
                admin_check();
            }
             
            
            }
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "ERROR");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        password_log = new javax.swing.JPasswordField();
        student_log = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SignIn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 70));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(32767, 32767));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/MANN.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 160, 70, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/LOCKK.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 260, 60, 60);

        password_log.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(password_log);
        password_log.setBounds(190, 270, 220, 50);

        student_log.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        student_log.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        student_log.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jPanel1.add(student_log);
        student_log.setBounds(190, 170, 220, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/finalestlogo.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 0, 210, 120);

        SignIn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        SignIn.setText("Sign In");
        SignIn.setBorder(new javax.swing.border.MatteBorder(null));
        SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInActionPerformed(evt);
            }
        });
        jPanel1.add(SignIn);
        SignIn.setBounds(230, 350, 130, 31);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Create New Account");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(200, 420, 200, 25);

        jLabel4.setFont(new java.awt.Font("Sofachrome Rg", 1, 24)); // NOI18N
        jLabel4.setText(" Login");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(240, 50, 150, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/finalregisterback.jpg"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(832, 607));
        jLabel5.setMinimumSize(new java.awt.Dimension(832, 607));
        jLabel5.setPreferredSize(new java.awt.Dimension(832, 607));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 620, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInActionPerformed
null_check();        // TODO add your handling code here:
    }//GEN-LAST:event_SignInActionPerformed

    
    public void admin_check()
    {
        String studentlog= student_log.getText();
        studentlog_=studentlog;
        String passlog=password_log.getText();
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "system", "123456");
            stmt = con.createStatement();
            ResultSet rs1= stmt.executeQuery("SELECT * FROM ADMIN WHERE ADMIN_ID='"+studentlog+"' AND ADMIN_PASS='"+passlog+"'");
            
            if (rs1.next())
            {
                JOptionPane.showMessageDialog(null,"Login Successful");
                this.setVisible(false);
                 Admin_Events aeve=new Admin_Events();
                aeve.setVisible(true);
            }
            
            else
            {
                JOptionPane.showMessageDialog(null, "Incorrect Credentials.");
            }
             
            
            }
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "ERROR");
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         System.out.println("button");
         try{
             System.out.print("try");
             this.setVisible(false);
        Kiosk_Register kreg = new Kiosk_Register();
kreg.setVisible(true);}
catch(Exception e)
{
    System.out.println("catch");
    e.printStackTrace();
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kiosk_Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kiosk_Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kiosk_Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kiosk_Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kiosk_Log().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignIn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password_log;
    private javax.swing.JTextField student_log;
    // End of variables declaration//GEN-END:variables
}
