/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kiosk;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Aasna
 */
public class Profile_View extends javax.swing.JFrame {
    Connection con = null;
    Statement stmt = null;
    PreparedStatement ps = null;

    /**
     * Creates new form Profile_Update
     */
    public Profile_View() {
        initComponents();
        propic.setBackground(Color.YELLOW);
                setDefaultCloseOperation(Profile_View.DISPOSE_ON_CLOSE);
                displaying();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        levelview = new javax.swing.JLabel();
        fullnameview = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        contactview = new javax.swing.JLabel();
        addressview = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        propic = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 255));
        setLocation(new java.awt.Point(300, 100));
        setMinimumSize(new java.awt.Dimension(550, 500));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jButton1.setText("My Bookings");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 60, 120, 30);

        jLabel1.setFont(new java.awt.Font("Sofachrome Rg", 0, 14)); // NOI18N
        jLabel1.setText("MY Profile");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 50, 144, 44);

        levelview.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        levelview.setText("Student Level");
        getContentPane().add(levelview);
        levelview.setBounds(160, 190, 89, 20);

        fullnameview.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        fullnameview.setText("Full Name");
        getContentPane().add(fullnameview);
        fullnameview.setBounds(160, 140, 83, 28);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/finalestlogo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, -10, 220, 130);

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel3.setText("Full Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 140, 83, 28);

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel4.setText("Student Level");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(39, 187, 89, 25);

        contactview.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        contactview.setText("Contact No");
        getContentPane().add(contactview);
        contactview.setBounds(160, 230, 83, 24);

        addressview.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        addressview.setText("Address");
        getContentPane().add(addressview);
        addressview.setBounds(160, 280, 83, 24);

        update.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(178, 344, 94, 27);

        propic.setBackground(new java.awt.Color(102, 0, 153));
        propic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/Capture4.JPG"))); // NOI18N
        propic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(propic);
        propic.setBounds(327, 130, 174, 170);

        jLabel9.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel9.setText("Contact No");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(39, 235, 83, 24);

        jLabel11.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel11.setText("Address");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(39, 284, 83, 24);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/brandi-redd-122054-unsplash.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 540, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
this.dispose();
        Profile_Update proup=new Profile_Update();
proup.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
MyBookings mbk= new MyBookings();
mbk.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
public void displaying()
{
    Kiosk_Log klog = new Kiosk_Log();
    String userview=klog.studentlog_;
    try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "system", "123456");
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM PROFILE WHERE STUDENT_NO='"+userview+"'");
            if (rs.next())
            {
                fullnameview.setText(rs.getString("FULL_NAME"));
                levelview.setText(rs.getString("STUDENT_LEVEL"));
                contactview.setText(rs.getString("CONTACT"));
                addressview.setText(rs.getString("ADDRESS"));
                byte[] imgData = null;
                 Blob img  = rs.getBlob("PICTURE");
                 imgData = img.getBytes(1,(int)img.length());
   BufferedImage image = ImageIO.read(new ByteArrayInputStream(imgData));
   
   propic.setIcon(new ImageIcon(image.getScaledInstance(propic.getWidth(), propic.getHeight(),Image.SCALE_SMOOTH)));
            }
            
            else
            {
                System.out.println("No data");
            }
             
            
            }
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "ERROR");
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressview;
    private javax.swing.JLabel contactview;
    private javax.swing.JLabel fullnameview;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel levelview;
    private javax.swing.JLabel propic;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
