/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kiosk;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.proteanit.sql.DbUtils;

public class GUI_Kiosk extends javax.swing.JFrame {

   
  Connection con1=null;
    Statement st1=null;
    PreparedStatement ps1= null;
    ResultSet rs=null;
    FileInputStream imageInputStream = null;
    static String path;
    public GUI_Kiosk() {
        initComponents();
        showTableData();
        showTableData1();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Hometab = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        seebtn1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        seebtn2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        seebtn3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        seebtn4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        seebtn5 = new javax.swing.JButton();
        Eventstab = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        clzevent = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jLabel37 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        evnt_id = new javax.swing.JTextField();
        evnt_name = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        time = new javax.swing.JTextField();
        desc = new javax.swing.JTextField();
        admin_id = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnupdate1 = new javax.swing.JButton();
        btndelete1 = new javax.swing.JButton();
        btnsearch1 = new javax.swing.JButton();
        imglevel = new javax.swing.JLabel();
        btnchoose = new javax.swing.JButton();
        cmtevent = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();
        Gallerytab = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        cmtimg = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        clzimg = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        Helptab = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        Userstab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        std_id = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        btnsrch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1314, 700));

        jTabbedPane1.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N

        Hometab.setFont(new java.awt.Font("Chiller", 1, 14)); // NOI18N
        Hometab.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/priscilla-du-preez-775570-unsplash.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 204)));
        Hometab.add(jLabel6);
        jLabel6.setBounds(0, 128, 205, 190);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/martins-zemlickis-57243-unsplash.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 204)));
        Hometab.add(jLabel5);
        jLabel5.setBounds(248, 127, 202, 190);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/md-duran-628456-unsplash.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 204)));
        Hometab.add(jLabel7);
        jLabel7.setBounds(493, 127, 192, 190);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/kal-visuals-705792-unsplash.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 204)));
        Hometab.add(jLabel8);
        jLabel8.setBounds(736, 127, 188, 190);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/Football.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 204)));
        Hometab.add(jLabel9);
        jLabel9.setBounds(970, 130, 193, 190);

        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.setFont(new java.awt.Font("Chiller", 3, 36)); // NOI18N
        jTextField1.setText("TOP 5 EVENTS");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        Hometab.add(jTextField1);
        jTextField1.setBounds(489, 43, 196, 48);

        jButton1.setFont(new java.awt.Font("Chiller", 3, 24)); // NOI18N
        jButton1.setText("Change Events");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Hometab.add(jButton1);
        jButton1.setBounds(1000, 400, 160, 37);

        jLabel10.setFont(new java.awt.Font("Baskerville Old Face", 3, 18)); // NOI18N
        jLabel10.setText("The Musical Night");
        Hometab.add(jLabel10);
        jLabel10.setBounds(20, 320, 160, 30);

        seebtn1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seebtn1.setText("see details");
        Hometab.add(seebtn1);
        seebtn1.setBounds(50, 350, 100, 23);

        jLabel13.setFont(new java.awt.Font("Baskerville Old Face", 3, 18)); // NOI18N
        jLabel13.setText("The Marathon");
        Hometab.add(jLabel13);
        jLabel13.setBounds(290, 320, 130, 19);

        seebtn2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seebtn2.setText("see details");
        Hometab.add(seebtn2);
        seebtn2.setBounds(310, 350, 93, 23);

        jLabel14.setFont(new java.awt.Font("Baskerville Old Face", 3, 18)); // NOI18N
        jLabel14.setText("The Graduation Ceremony");
        Hometab.add(jLabel14);
        jLabel14.setBounds(480, 320, 220, 19);

        seebtn3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seebtn3.setText("see details");
        Hometab.add(seebtn3);
        seebtn3.setBounds(540, 350, 100, 23);

        jLabel15.setFont(new java.awt.Font("Baskerville Old Face", 3, 18)); // NOI18N
        jLabel15.setText("Movie Making");
        Hometab.add(jLabel15);
        jLabel15.setBounds(770, 320, 120, 19);

        seebtn4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seebtn4.setText("see details");
        Hometab.add(seebtn4);
        seebtn4.setBounds(780, 350, 93, 23);

        jLabel16.setFont(new java.awt.Font("Baskerville Old Face", 3, 18)); // NOI18N
        jLabel16.setText("Sports Events");
        Hometab.add(jLabel16);
        jLabel16.setBounds(1010, 320, 120, 19);

        seebtn5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seebtn5.setText("see details");
        Hometab.add(seebtn5);
        seebtn5.setBounds(1020, 350, 100, 23);

        jTabbedPane1.addTab("Home", Hometab);

        jTabbedPane2.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        clzevent.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        clzevent.setPreferredSize(new java.awt.Dimension(1304, 1000));

        jScrollPane10.setPreferredSize(new java.awt.Dimension(1314, 600));

        Table1.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Event_Id", "Event Name", "Location", "Time", "Event_Date", "Description", "Admin_Id", "Event_Image"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane11.setViewportView(Table1);

        jLabel37.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel37.setText("Event Details");

        jLabel40.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel40.setText("Event Id ");

        jLabel42.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel42.setText("Event Name");

        jLabel43.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel43.setText("Location");

        jLabel44.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel44.setText("Time");

        jLabel45.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel45.setText("Event Date");

        jLabel46.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel46.setText("Description");

        jLabel47.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel47.setText("Admin Id");

        jLabel48.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel48.setText("Event Image");

        evnt_id.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        evnt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evnt_idActionPerformed(evt);
            }
        });

        evnt_name.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        location.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        time.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });

        desc.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        admin_id.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        btnadd.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnadd.setText("Add Event");

        btnupdate1.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnupdate1.setText("Update Event");
        btnupdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdate1ActionPerformed(evt);
            }
        });

        btndelete1.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btndelete1.setText("Delete Event");
        btndelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelete1ActionPerformed(evt);
            }
        });

        btnsearch1.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnsearch1.setText("Search");
        btnsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearch1ActionPerformed(evt);
            }
        });

        imglevel.setBorder(new javax.swing.border.MatteBorder(null));

        btnchoose.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnchoose.setText("Choose Image");
        btnchoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchooseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(btnupdate1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(btndelete1)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(jLabel37))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel40)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel48))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(admin_id, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(desc, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(time, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(location, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(evnt_name, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(evnt_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                                        .addGap(75, 75, 75)
                                        .addComponent(btnsearch1))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(imglevel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(btnchoose)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 939, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(120, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(jLabel40))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(evnt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnsearch1))))
                                .addGap(58, 58, 58)
                                .addComponent(evnt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel42)))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44))
                        .addGap(57, 57, 57)
                        .addComponent(jLabel45)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel46))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel47))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(admin_id, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imglevel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel48)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(btnchoose, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnupdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btndelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(148, 148, 148))))
        );

        jScrollPane10.setViewportView(jPanel5);

        javax.swing.GroupLayout clzeventLayout = new javax.swing.GroupLayout(clzevent);
        clzevent.setLayout(clzeventLayout);
        clzeventLayout.setHorizontalGroup(
            clzeventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 1304, Short.MAX_VALUE)
        );
        clzeventLayout.setVerticalGroup(
            clzeventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 1106, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("College Events", clzevent);

        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(Table2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(450, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel2);

        javax.swing.GroupLayout cmteventLayout = new javax.swing.GroupLayout(cmtevent);
        cmtevent.setLayout(cmteventLayout);
        cmteventLayout.setHorizontalGroup(
            cmteventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
        cmteventLayout.setVerticalGroup(
            cmteventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmteventLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 304, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Community Events", cmtevent);

        javax.swing.GroupLayout EventstabLayout = new javax.swing.GroupLayout(Eventstab);
        Eventstab.setLayout(EventstabLayout);
        EventstabLayout.setHorizontalGroup(
            EventstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        EventstabLayout.setVerticalGroup(
            EventstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EventstabLayout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Events", Eventstab);

        jTabbedPane3.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable2);

        javax.swing.GroupLayout cmtimgLayout = new javax.swing.GroupLayout(cmtimg);
        cmtimg.setLayout(cmtimgLayout);
        cmtimgLayout.setHorizontalGroup(
            cmtimgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmtimgLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 2016, Short.MAX_VALUE)
                .addContainerGap())
        );
        cmtimgLayout.setVerticalGroup(
            cmtimgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmtimgLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 381, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Community Events Images", cmtimg);

        clzimg.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Club Events", "Students Nights", "Guest Lectures", "Workshops"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable3);

        javax.swing.GroupLayout clzimgLayout = new javax.swing.GroupLayout(clzimg);
        clzimg.setLayout(clzimgLayout);
        clzimgLayout.setHorizontalGroup(
            clzimgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clzimgLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1139, Short.MAX_VALUE))
        );
        clzimgLayout.setVerticalGroup(
            clzimgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clzimgLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("College Events Images", clzimg);

        jScrollPane3.setViewportView(jTabbedPane3);
        jTabbedPane3.getAccessibleContext().setAccessibleName("Community Events Images");

        javax.swing.GroupLayout GallerytabLayout = new javax.swing.GroupLayout(Gallerytab);
        Gallerytab.setLayout(GallerytabLayout);
        GallerytabLayout.setHorizontalGroup(
            GallerytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1309, Short.MAX_VALUE)
        );
        GallerytabLayout.setVerticalGroup(
            GallerytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GallerytabLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Gallery", Gallerytab);

        Helptab.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("How can we help you?");

        jLabel17.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel17.setText("Do you need help in login or registration?");

        jLabel36.setBackground(new java.awt.Color(153, 153, 255));
        jLabel36.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 51, 204));
        jLabel36.setText("Drop your problems and we will find suggestions for you....");

        javax.swing.GroupLayout HelptabLayout = new javax.swing.GroupLayout(Helptab);
        Helptab.setLayout(HelptabLayout);
        HelptabLayout.setHorizontalGroup(
            HelptabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HelptabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HelptabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel17)
                    .addComponent(jLabel36))
                .addContainerGap(680, Short.MAX_VALUE))
        );
        HelptabLayout.setVerticalGroup(
            HelptabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HelptabLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(168, 168, 168)
                .addComponent(jLabel17)
                .addGap(140, 140, 140)
                .addComponent(jLabel36)
                .addContainerGap(916, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Help", Helptab);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel38.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel38.setText("Student's Information");

        jLabel39.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel39.setText("Student id");

        jLabel41.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel41.setText("Email");

        std_id.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        std_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_idActionPerformed(evt);
            }
        });

        email.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N

        btndelete.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnupdate.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        Table.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Student_id", "Email"
            }
        ));
        jScrollPane2.setViewportView(Table);

        btnsrch.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnsrch.setText("Search");
        btnsrch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsrchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel38))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btndelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addComponent(btnupdate))
                            .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(std_id, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(49, 49, 49)
                        .addComponent(btnsrch, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel38)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(std_id, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnsrch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(83, 83, 83))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel41)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(807, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout UserstabLayout = new javax.swing.GroupLayout(Userstab);
        Userstab.setLayout(UserstabLayout);
        UserstabLayout.setHorizontalGroup(
            UserstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1309, Short.MAX_VALUE)
        );
        UserstabLayout.setVerticalGroup(
            UserstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.addTab("Users", Userstab);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/KIosksmallLogo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("KIOSK");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel11.setText("Kiosk at your service.");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel12.setText("Online platform to get all the events information.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel3.setText("XYZ's Name");

        btnlogout.setFont(new java.awt.Font("Chiller", 1, 18)); // NOI18N
        btnlogout.setText("Log Out");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(btnlogout))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3822, 3822, 3822))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnsrchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsrchActionPerformed
         try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:kiosk","SYSTEM","1234Kamu");
            st1= con1.createStatement();
            String sid=std_id.getText();
            System.out.println(sid);
           //  ps1.setString(1, std_id.getText());
            rs = st1.executeQuery("SELECT * FROM TEST1 WHERE STUDENT_ID='"+sid+"'");
            if (rs.next()){
            email.setText(rs.getString("EMAIL"));
        }
         }
        catch(Exception ex){
        JOptionPane.showMessageDialog(null,ex);
        
    }
    }//GEN-LAST:event_btnsrchActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:kiosk","SYSTEM","1234Kamu");
            st1= con1.createStatement();
            String email1= email.getText();
            String std1=std_id.getText();
            String sql="DELETE FROM TEST1 WHERE STUDENT_ID='"+std1+"'";
            ps1=con1.prepareStatement(sql);
            rs=ps1.executeQuery();
            JOptionPane.showMessageDialog(null,"Deleted Successfully");
            showTableData();
            std_id.setText(" ");
            email.setText(" ");
            rs.close();
            con1.close();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        
    }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        String email1= email.getText();
        String std1=std_id.getText();
        try{
         Class.forName("oracle.jdbc.driver.OracleDriver");
        con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:kiosk","SYSTEM","1234Kamu");
        st1= con1.createStatement();
        String sql="UPDATE TEST1 SET EMAIL='"+email1+"' where STUDENT_ID='"+std1+"'";
        ps1=con1.prepareStatement(sql);
        rs=ps1.executeQuery();
        JOptionPane.showMessageDialog(null,"Updated Successfully");
        showTableData();
        
        
        rs.close();
        con1.close();
    }
    catch(Exception ex){
        JOptionPane.showMessageDialog(null,ex);
        
    }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void std_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_idActionPerformed

    private void evnt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evnt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_evnt_idActionPerformed

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    private void btnupdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdate1ActionPerformed
        String eid=evnt_id.getText();
        String ename=evnt_name.getText();
        String elocation=location.getText();
        String etime=time.getText();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        date.setFormats(dateFormat);
        String date_to_store = dateFormat.format(date.getDate()).toString();
        String edescrip=desc.getText();
        String eadmin=admin_id.getText();
        String dateFormatted = "TO_DATE('"+date_to_store+"', 'DD-MM-YYYY')";
        
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:kiosk","SYSTEM","1234Kamu");
            st1= con1.createStatement();
            
            
            String sql="UPDATE COLLEGEEVENT SET EVENT_NAME='"+ename+"',LOCATION='"+elocation+"',TIME='"+etime+"',EVENT_DATE='"TO_DATE('"+date_to_store+"', 'DD-MM-YYYY')"',
                + "DESCRIPTION='"+edescrip+"',ADMINID='"+eadmin+"',EVENT_IMAGE=? WHERE EVENT_ID='"+eid+"'";
            ps1=con1.prepareStatement(sql);
            imageInputStream = new FileInputStream(new File(path));
            ps1.setBinaryStream(1, imageInputStream);
            rs=ps1.executeQuery();
            JOptionPane.showMessageDialog(null,"Updated Successfully");
            showTableData1();
            rs.close();
            con1.close();
             
		    
                    // execute query
		    
    }
    catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        
    }
    }//GEN-LAST:event_btnupdate1ActionPerformed

    private void btnsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearch1ActionPerformed
        String eid=evnt_id.getText();
        String ename=evnt_name.getText();
        String elocation=location.getText();
        String etime=time.getText();
        String edate=date.getText();
        String edescrip=desc.getText();
        String eadmin=admin_id.getText();
        
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:kiosk","SYSTEM","1234Kamu");
            st1= con1.createStatement();
            System.out.println(eid);
           //  ps1.setString(1, std_id.getText());
            rs = st1.executeQuery("SELECT * FROM COLLEGEEVENT WHERE EVENT_ID='"+eid+"'");
            if (rs.next()){
            evnt_name.setText(rs.getString("EVENT_NAME"));
            location.setText(rs.getString("LOCATION"));
            time.setText(rs.getString("TIME"));
            date.setText(rs.getString("EVENT_DATE"));
            desc.setText(rs.getString("DESCRIPTION"));
            admin_id.setText(rs.getString("ADMINID"));
            byte[] imgData = null;
                 Blob img  = rs.getBlob("EVENT_IMAGE");
                 imgData = img.getBytes(1,(int)img.length());
   BufferedImage image = ImageIO.read(new ByteArrayInputStream(imgData));
    imglevel.setIcon(new ImageIcon(image.getScaledInstance(imglevel.getWidth(),imglevel.getHeight(),Image.SCALE_SMOOTH)));
            
        }
         }
        catch(Exception ex){
        JOptionPane.showMessageDialog(null,ex);
        
    }
    }//GEN-LAST:event_btnsearch1ActionPerformed

    private void btndelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelete1ActionPerformed
        String eid=evnt_id.getText();
        String ename=evnt_name.getText();
        String elocation=location.getText();
        String etime=time.getText();
        String edate=date.getText();
        String edescrip=desc.getText();
        String eadmin=admin_id.getText();
       
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:kiosk","SYSTEM","1234Kamu");
            st1= con1.createStatement();
            String sql="DELETE FROM COLLEGEEVENT WHERE EVENT_ID='"+eid+"'";
            ps1=con1.prepareStatement(sql);
            rs=ps1.executeQuery();
            JOptionPane.showMessageDialog(null,"Deleted Successfully");
            showTableData1();
            evnt_id.setText(" ");
            evnt_name.setText(" ");
            location.setText(" ");
            time.setText(" ");
            date.setText(" ");
            desc.setText(" ");
            admin_id.setText(" ");
            
            rs.close();
            con1.close();
        }
        catch(Exception ex){
        JOptionPane.showMessageDialog(null,ex);
        
    }
    }//GEN-LAST:event_btndelete1ActionPerformed

    private void btnchooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchooseActionPerformed
 JFileChooser file = new JFileChooser();
          file.setCurrentDirectory(new File(System.getProperty("user.home")));
          //filter the files
          FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
          file.addChoosableFileFilter(filter);
          int result = file.showSaveDialog(null);
           //if the user click on save in Jfilechooser
          if(result == JFileChooser.APPROVE_OPTION){
              File selectedFile = file.getSelectedFile();
              String path = selectedFile.getAbsolutePath();
              imglevel.setIcon(ResizeImage(path));
          }        // TODO add your handling code here:
    }//GEN-LAST:event_btnchooseActionPerformed

      public ImageIcon ResizeImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(imglevel.getWidth(), imglevel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

   public void showTableData(){
       try{
        Class.forName("oracle.jdbc.driver.OracleDriver");
        con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:kiosk","system","1234Kamu");
        st1= con1.createStatement();
      
        rs = st1.executeQuery("select * from TEST1");
        System.out.print("running");
        Table.setModel(DbUtils.resultSetToTableModel(rs));
      }
    catch(Exception ex){
        JOptionPane.showMessageDialog(null,ex);
        
    }
   }
   public void showTableData1()
   {
       try{
        Class.forName("oracle.jdbc.driver.OracleDriver");
        con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:kiosk","system","1234Kamu");
        st1= con1.createStatement();
      
        rs = st1.executeQuery("select * from COLLEGEEVENT");
        System.out.print("running");
        Table1.setModel(DbUtils.resultSetToTableModel(rs));
      }
    catch(Exception ex){
        JOptionPane.showMessageDialog(null,ex);
        
    }
   }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Kiosk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Kiosk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Kiosk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Kiosk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Kiosk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Eventstab;
    private javax.swing.JPanel Gallerytab;
    private javax.swing.JPanel Helptab;
    private javax.swing.JPanel Hometab;
    private javax.swing.JTable Table;
    private javax.swing.JTable Table1;
    private javax.swing.JTable Table2;
    private javax.swing.JPanel Userstab;
    private javax.swing.JTextField admin_id;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnchoose;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btndelete1;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnsearch1;
    private javax.swing.JButton btnsrch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btnupdate1;
    private javax.swing.JPanel clzevent;
    private javax.swing.JPanel clzimg;
    private javax.swing.JPanel cmtevent;
    private javax.swing.JPanel cmtimg;
    private javax.swing.JTextField desc;
    private javax.swing.JTextField email;
    private javax.swing.JTextField evnt_id;
    private javax.swing.JTextField evnt_name;
    private javax.swing.JLabel imglevel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField location;
    private javax.swing.JButton seebtn1;
    private javax.swing.JButton seebtn2;
    private javax.swing.JButton seebtn3;
    private javax.swing.JButton seebtn4;
    private javax.swing.JButton seebtn5;
    private javax.swing.JTextField std_id;
    private javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables
}
