package kiosk;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sujan
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class Kiosk_Register extends javax.swing.JFrame {
    Connection con = null;
    Statement stmt = null;
    PreparedStatement ps = null;

    /**
     * Creates new form Kiosk_Register
     */
    public Kiosk_Register() {
        initComponents();
        setDefaultCloseOperation(Kiosk_Register.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        password_reg = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        studentno_reg = new javax.swing.JTextField();
        email_reg = new javax.swing.JTextField();
        signup = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 50));
        setMinimumSize(new java.awt.Dimension(500, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/Sam.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 250, 60, 50);

        password_reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                password_regMouseEntered(evt);
            }
        });
        password_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_regActionPerformed(evt);
            }
        });
        getContentPane().add(password_reg);
        password_reg.setBounds(200, 340, 250, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/LOCKK.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 330, 60, 60);

        studentno_reg.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        studentno_reg.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        studentno_reg.setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        studentno_reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentno_regMouseEntered(evt);
            }
        });
        studentno_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentno_regActionPerformed(evt);
            }
        });
        getContentPane().add(studentno_reg);
        studentno_reg.setBounds(200, 170, 250, 50);

        email_reg.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        email_reg.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        email_reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                email_regMouseEntered(evt);
            }
        });
        email_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_regActionPerformed(evt);
            }
        });
        getContentPane().add(email_reg);
        email_reg.setBounds(200, 250, 250, 50);

        signup.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        signup.setForeground(new java.awt.Color(0, 0, 51));
        signup.setText("Sign Up");
        signup.setBorder(new javax.swing.border.MatteBorder(null));
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup);
        signup.setBounds(250, 420, 140, 40);

        jLabel2.setFont(new java.awt.Font("Sofachrome Rg", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Registration");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 50, 330, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/finalestlogo.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-10, -10, 210, 140);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/MANN.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 160, 50, 60);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/finalregisterback.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-20, -140, 680, 800);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
registering();        

    }//GEN-LAST:event_signupActionPerformed

    public void registering()
    {
        String studentno_reg1 = studentno_reg.getText();
        String email_reg1=email_reg.getText();
        String password_reg1=password_reg.getText();
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "system", "123456");
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("INSERT INTO REGISTER(STUDENT_NO,STUDENT_EMAIL,STUDENT_PASSWORD) VALUES ('"+studentno_reg1+"','"+email_reg1+"','"+password_reg1+"')");
            System.out.println("Sucessfully Inserted");
             JOptionPane.showMessageDialog(null, "Registration Successfully!");
             this.setVisible(false);
             Kiosk_Log klog=new Kiosk_Log();
             klog.setVisible(true);
            
            }
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "ERROR");
        }
    }
    private void studentno_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentno_regActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentno_regActionPerformed

    private void email_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_regActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_regActionPerformed

    private void password_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_regActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_regActionPerformed

    private void studentno_regMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentno_regMouseEntered
studentno_reg.setToolTipText("Your Student Number");        // TODO add your handling code here:
    }//GEN-LAST:event_studentno_regMouseEntered

    private void email_regMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_email_regMouseEntered
email_reg.setToolTipText("Your Email");        // TODO add your handling code here:
    }//GEN-LAST:event_email_regMouseEntered

    private void password_regMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_password_regMouseEntered
password_reg.setToolTipText("Your Password");        // TODO add your handling code here:
    }//GEN-LAST:event_password_regMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kiosk_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kiosk_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kiosk_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kiosk_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kiosk_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email_reg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField password_reg;
    private javax.swing.JButton signup;
    private javax.swing.JTextField studentno_reg;
    // End of variables declaration//GEN-END:variables
}
