/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kiosk;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Aasna
 */
public class Profile_Update extends javax.swing.JFrame {
    Connection con = null;
    Statement stmt = null;
    PreparedStatement ps = null;


    /**
     * Creates new form Profile_Update
     */
    public Profile_Update() {
        initComponents();
        propic.setBackground(Color.YELLOW);
                setDefaultCloseOperation(Profile_Update.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fullnameupdate = new javax.swing.JTextField();
        studentlevelupdate = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        propic = new javax.swing.JLabel();
        contactupdate = new javax.swing.JTextField();
        addressupdate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 255));
        setLocation(new java.awt.Point(300, 100));
        setMinimumSize(new java.awt.Dimension(550, 500));
        setPreferredSize(new java.awt.Dimension(550, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sofachrome Rg", 0, 14)); // NOI18N
        jLabel1.setText("Update Profile");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 50, 209, 44);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/finalestlogo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 0, 220, 110);

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel3.setText("Full Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(39, 137, 83, 28);

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel4.setText("Student Level");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(39, 187, 89, 25);

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel5.setText("Contact No");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(39, 235, 83, 24);

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(39, 284, 83, 24);
        getContentPane().add(fullnameupdate);
        fullnameupdate.setBounds(146, 130, 163, 42);

        studentlevelupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentlevelupdateActionPerformed(evt);
            }
        });
        getContentPane().add(studentlevelupdate);
        studentlevelupdate.setBounds(146, 178, 163, 42);

        update.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(178, 344, 94, 27);

        jButton2.setFont(new java.awt.Font("Baskerville Old Face", 1, 12)); // NOI18N
        jButton2.setText("Upload Photo");
        getContentPane().add(jButton2);
        jButton2.setBounds(360, 320, 113, 21);

        propic.setBackground(new java.awt.Color(102, 0, 153));
        propic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/Capture4.JPG"))); // NOI18N
        propic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(propic);
        propic.setBounds(327, 130, 174, 170);

        contactupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactupdateActionPerformed(evt);
            }
        });
        getContentPane().add(contactupdate);
        contactupdate.setBounds(146, 226, 163, 42);

        addressupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressupdateActionPerformed(evt);
            }
        });
        getContentPane().add(addressupdate);
        addressupdate.setBounds(146, 275, 163, 42);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiosk/brandi-redd-122054-unsplash.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 540, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentlevelupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentlevelupdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentlevelupdateActionPerformed

    private void contactupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactupdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactupdateActionPerformed

    private void addressupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressupdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressupdateActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
    null_check();    // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed
 public void updating()
    {
        Kiosk_Log klog=new Kiosk_Log();
        
        String  full_name=fullnameupdate.getText();
        String level_=studentlevelupdate.getText();
        String contact_=contactupdate.getText();
        String address_=addressupdate.getText();
        String username_=klog.studentlog_;
        
        
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "system", "123456");
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("INSERT INTO PROFILE(USERNAME,FULL_NAME,STUDENT_LEVEL,CONTACT,ADDRESS) VALUES ('"+username_+"','"+full_name+"','"+level_+"','"+contact_+"','"+address_+"')");
            System.out.println("Sucessfully Inserted");
             JOptionPane.showMessageDialog(null, "Inserted Successfully!");
             this.setVisible(false);
             Profile_View pview= new Profile_View();
             pview.setVisible(true);
             
            
            }
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "ERROR");
        }
    }
 
 public void null_check()
 {
     String  full_name=fullnameupdate.getText();
        String level_=studentlevelupdate.getText();
        String contact_=contactupdate.getText();
        String address_=addressupdate.getText();
        
        if (full_name==" " || level_==" " || contact_==" "|| address_==" ")
        {
            JOptionPane.showMessageDialog(null, "Please fill out all the fields.");
        }
        
        else
        {
            updating();
        }
     
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile_Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressupdate;
    private javax.swing.JTextField contactupdate;
    private javax.swing.JTextField fullnameupdate;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel propic;
    private javax.swing.JTextField studentlevelupdate;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
